[supabase]
url = "https://vnavtkwkxelradnrsnsb.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZuYXZ0a3dreGVscmFkbnJzbnNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODkyNTIsImV4cCI6MjA2NTU2NTI1Mn0.YCjq2FhsgJgtuZgmDVpOVE_Zki1JmQixhYOF-0GWk70"